<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLabSkl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLabSkl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXLabSkl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXLabSkl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXLabSkl\App_KernelDevDebugContainer([
    'container.build_hash' => 'XLabSkl',
    'container.build_id' => 'eebc1776',
    'container.build_time' => 1575325444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLabSkl');
